from .aquatic import IAquatic
from .flying import IFlying
from .freshwater import IFreshwater
from .saltwater import ISaltwater
from .freshsaltwater import IFreshSaltwater
from .stagnant import IStagnant
from .swimming import ISwimming
from .walking import IWalking
from .shade import IShade